In [1]:
import numpy as np

## Datatypes and Attributes
 Numpy's main datatype is ndarray  

In [2]:
arr = np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [3]:
type(arr)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Attributes

In [6]:
print(f'Shape -> {a3.shape}')#prints out the shape of array
print(f'dimension -> {a3.ndim}') #number of dimensions in array
print(f'Type -> {a3.dtype}')#to know the data type of elements in the array
print(f'Size-> {a3.size}') #number of elements in the array

Shape -> (2, 3, 3)
dimension -> 3
Type -> int32
Size-> 18


## Creating dataframe from NumPy array

In [7]:
import pandas as pd 
df = pd.DataFrame(a2)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

## Creating arrays

In [8]:
ones = np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[8, 2, 2, 9, 4],
       [4, 6, 4, 5, 5],
       [8, 1, 3, 5, 7]])

In [12]:
random_array_2 = np.random.rand(5, 3)
random_array_2

array([[6.87931883e-01, 5.72794512e-04, 5.71220637e-02],
       [9.72125830e-01, 4.83894463e-01, 5.35913950e-01],
       [3.87851913e-01, 6.22708046e-01, 1.50341017e-01],
       [9.53825112e-01, 4.54310873e-01, 7.61255832e-01],
       [6.41406594e-01, 4.54860199e-01, 8.28743718e-01]])

In [13]:
# pseudo random numbers
# np.random.seed() -> generate random numbers that are reproducable
np.random.seed(seed = 0)
random_array_3 = np.random.randint(10, size=(5, 3))
random_array_3


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and Matrices

In [14]:
# Finding unique elements in an array
np.unique(random_array_3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
random_array_4 = np.random.randint(10, size=(2,3,4,5))
random_array_4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [16]:
random_array_4.shape

(2, 3, 4, 5)

In [17]:
random_array_4[:, :, :, :3]

array([[[[6, 7, 7],
         [5, 9, 8],
         [3, 0, 3],
         [2, 3, 8]],

        [[3, 3, 7],
         [9, 9, 0],
         [3, 2, 7],
         [0, 4, 5]],

        [[8, 4, 1],
         [8, 1, 1],
         [9, 3, 6],
         [0, 3, 5]]],


       [[[4, 6, 4],
         [4, 4, 8],
         [7, 5, 5],
         [5, 9, 3]],

        [[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0],
         [2, 9, 2]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0],
         [0, 6, 3]]]])

## -------------------------------------------------------------------

## Manipulating & comparing arrays
### Arithmetic

In [18]:
arr

array([1, 2, 3, 4])

In [19]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [20]:
arr + ones
# other arithmetic operations
'''
/, -, *, **, %, //
np.add(a1, a2)
np.square(a1)
np.exp(a1)
np.log(a1)
'''

'\n/, -, *, **, %, //\nnp.add(a1, a2)\nnp.square(a1)\nnp.exp(a1)\nnp.log(a1)\n'

### Aggreation
Aggreation = performing the same operation on a numer of things

use Python's methods (`sum()`) on python datatyes and use NumPy's methods (`np.sum()`) on NumPy arays 

In [21]:
# creating a massive array
massive_array = np.random.random(1000)
massive_array.size

1000

In [22]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [23]:
%timeit sum(massive_array) #python sum
%timeit np.sum(massive_array) #NumPy sum

1.19 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
43.2 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
#other aggregate functions
'''
np.mean(arr)
np.max(arr)
np.min(arr)
np.sqrt()
np.std(arr) -> A measure of how spread out a group of numbers is from the mean
            ->std = sqrt(var)
            
np.var(arr) ->meausre of average degree to which each number is different to the mean
            ->Higher variance = wider range of numbers
            ->lower varience = lower range of numbers 
'''

'\nnp.mean(arr)\nnp.max(arr)\nnp.min(arr)\nnp.sqrt()\nnp.std(arr) -> A measure of how spread out a group of numbers is from the mean\n            ->std = sqrt(var)\n            \nnp.var(arr) ->meausre of average degree to which each number is different to the mean\n            ->Higher variance = wider range of numbers\n            ->lower varience = lower range of numbers \n'

## Resahping and Transposing

In [37]:
a2= np.random.randint(10, size=(2,3))
a2

array([[1, 9, 3],
       [1, 0, 7]])

In [38]:
a2.shape

(2, 3)

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [29]:
# rules of broadcasting
#1. dimensions of both the array should be equal
#2. or one of the dimension should be 1

In [41]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [9],
        [3]],

       [[1],
        [0],
        [7]]])

In [42]:
a2_reshape * a3

array([[[  1,   2,   3],
        [ 36,  45,  54],
        [ 21,  24,  27]],

       [[ 10,  11,  12],
        [  0,   0,   0],
        [112, 119, 126]]])

In [43]:
# Transpose = swapp the axis
a2.T

array([[1, 1],
       [9, 0],
       [3, 7]])

In [44]:
a2.shape

(2, 3)

## Dot Product

In [45]:
mat1 = np.random.randint(10,size=(3,3))
mat2 = np.random.randint(10,size=(3,2))


In [46]:
mat1

array([[3, 9, 6],
       [4, 4, 3],
       [5, 4, 4]])

In [47]:
mat2

array([[9, 0],
       [0, 9],
       [5, 0]])

In [50]:
# note: for dot product the insside shape of the two input marix must match
# in this case the shapes are 3 * 3 , 3 * 2 the inside shape is 3 and 3
mat1.shape,mat2.shape

((3, 3), (3, 2))

In [48]:
np.dot(mat1,mat2)

array([[57, 81],
       [51, 36],
       [65, 36]])

## Dot product example

In [51]:
np.random.seed(0)
# Number of jars sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [53]:
weekly_sales = pd.DataFrame(sales_amount, index=["Mon","Tue","Wed","Thurs","Fri"],
columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [55]:
# Create price array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [58]:
# Create butter_price dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [59]:
total_sales =prices.dot(sales_amount)


ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [63]:
# Shapes not alligned so transpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [64]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [65]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [67]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [70]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### Comparison operators

In [75]:
a1 = np.array([1,2,3])

In [73]:
a2

array([[1, 9, 3],
       [1, 0, 7]])

In [76]:
a1 > a2

array([[False, False, False],
       [False,  True, False]])

In [77]:
# other operators 
# a1 >= a2
# a1 < a2
# a1 == a2

### Sorting Array

In [78]:
random_array

array([[8, 2, 2, 9, 4],
       [4, 6, 4, 5, 5],
       [8, 1, 3, 5, 7]])

In [79]:
np.sort(random_array)

array([[2, 2, 4, 8, 9],
       [4, 4, 5, 5, 6],
       [1, 3, 5, 7, 8]])

In [80]:
np.argsort(random_array)

array([[1, 2, 4, 0, 3],
       [0, 2, 3, 4, 1],
       [1, 2, 3, 4, 0]], dtype=int64)

In [81]:
# Turn an image into a numpy array
from matplotlib.image import imread

panda = imread("F:\zero-to-mastery-ml\images\panda.png")
type(panda)

numpy.ndarray

In [86]:
panda[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)